apiVersion: v1
kind: ConfigMap
metadata:
  name: httpdocs
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>	
    <head>
        <style>body{background-color:#d0e4fe;}h1{color:orange;text-align:center;}p{font-family:"Times New Roman";font-size:20px;}</style>
    </head>
    <body>	
    <button 
    type='button'
    onclick='javascript:
        var another_job = function() {
        new Ajax.Request("http://testuser:11b62eee8ec3959ba47fcbfeaaa8771e41@builder.localhost.com/job/dtm/build", {
            method: "post",
            parameters: {json: Object.toJSON({parameter: [{name: "foo", value: "fobar"}]})}
        });
    };
    another_job()'>
    Start Job
    </button>
    </body>
            </html>

