apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configsecret.name }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  APITOKEN:  {{ .Values.configsecret.apitoken }}
  USER: {{ .Values.configsecret.user }}
type: Opaque
